# Generated by Django 5.2.5 on 2025-08-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_internals', '0002_author_article_views_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='orm_internals.tag'),
        ),
    ]
