# Generated by Django 5.2.5 on 2025-09-01 19:43

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField()),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='product_metadata_gin_idx')],
            },
        ),
    ]
