# Generated by Django 5.2.5 on 2025-08-26 20:18

import custom_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('secret_content', custom_fields.fields.EncryptedTextField()),
            ],
        ),
    ]
