# Generated by Django 5.2.5 on 2025-08-30 22:40

from django.db import migrations

def split_full_name(apps, schema_editor):
    """
    Populate the new first_name and last_name fields from the existing full_name field.
    """
    Profile = apps.get_model('migrations_demo', 'Profile')
    for profile in Profile.objects.all():
        parts = profile.full_name.split(' ', 1)
        profile.first_name = parts[0]
        if len(parts) > 1:
            profile.last_name = parts[1]
        else:
            profile.last_name = ''
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('migrations_demo', '0002_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.RunPython(split_full_name)
    ]
